### ISSUE TITLE
clone the repo with msgs subfolder

### ISSUE THREAD

**Issue by martalorenz** [hrii-iit/xsens_mvn_ros#10]
To include the xsens_mvn_ros_msgs folder, you should git clone the repo with "--recursive". This should be included in the documentation

**Comment by mleonori** [comment]
Hi @martalorenz,

Thanks for opening the issue!

In the [build section](https://hrii-iit.github.io/xsens_mvn_ros/build.html) of the documentation you can find the `git clone` command that use `--recursive` option

**Comment by martalorenz** [comment]
Thank you very much, @mleonori
