### ISSUE TITLE
Questions about setting

### ISSUE THREAD

**Issue by jonyzhang2023** [hrii-iit/xsens_mvn_ros#12]
Thank you very much for your work. However, I still couldn't determine from the documentation how exactly to configure and execute the client. I have a few questions:
1. Do I need to use Xsens's router to put the Windows server and Linux client in the same LAN?
2. What else needs to be configured on the Linux client? How can the visualization in RViz be achieved as shown in the paper?

**Comment by mleonori** [comment]
Hi @jonyzhang2023,

thank you for opening this issue and I'm sorry for the lack of detailed documentation. I updated it (commit [d87825c](https://github.com/hrii-iit/xsens_mvn_ros/commit/d87825c4d82326b390cc66739a51c3fe0a457100)) trying to add information to reply your questions.

1. Exactly, in our configuration, we are using the Windows machine acting as a server connected to the XSens router and using MVN studio. This last one allows us to stream the data to a Linux client. These two machines have to be in the same LAN.
2. If the network and the MVN studio configuration are correct, you should be able to launch the client as reported in `Usage` section of the guide and visualize the topics. RViz should be launched by default.

Thanks again,

Mattia

**Comment by jonyzhang2023** [comment]
Thank you for your prompt and accurate response!
I am now able to use the server and client to communicate normally. Additionally, my data and equipment include xsens hand sensors, which adds 40 more links. Have you considered supporting hand data? Alternatively, I could write this part of the code and then submit a PR.

**Comment by mleonori** [comment]
I am glad the updated documentation helped you to fix the communication. 
Regarding the hand data support, it would be amazing if you want to participate and create a PR.
In this case, if you agree, I will close this issue, and open a new one for the hand data.

**Comment by jonyzhang2023** [comment]
Cool. Thanks for your kindness help!
