### ISSUE TITLE
Numbering of xsens/joints_states

### ISSUE THREAD

**Issue by emirmobedi** [hrii-iit/xsens_mvn_ros#6]
I would be nice in the main documentation to have the numbering of the joint_states so as to find them easily when you do not need all of them

**Comment by martalorenz** [comment]
Also a list of the links would be useful

**Comment by mleonori** [comment]
Hi @martalorenz,

In the [kinematic chain section](https://hrii-iit.github.io/xsens_mvn_ros/kinematic_chain.html#kinematics-chain) of the documentation, you can find the full list of the links and joints. If you think this list is complete and clear, we can close this issue

**Comment by martalorenz** [comment]
The list looks exhaustive now, thank you @mleonori ! We can close the issue.
